"""Typed shapes for the outreach engine (bead 1mk.7).

The outreach skills (outreach-sequence-builder + cold-email-verifier) are
prompt-only methodology; the *enforcement* — suppression-first, deliverability
verification, capped/spaced sequence, reply/bounce hard-stop, over-personalization
guard — is deterministic code in this package (the 1mk.3 pattern: adopt the skill
as a deterministic in-house validator, not an off-the-shelf classifier).

Safety posture baked into the types:
- **No auto-send.** Every plan is ``routed_to="review"`` (bead 439 hold: all
  channels MANUAL/escalate until rvy.7+rvy.8 pass on a real gold set).
- **PII discipline.** The auditable :class:`OutreachPlan` references a prospect by
  an opaque ``prospect_ref`` (a salted hash), never the raw email — logs/plans
  stay PII-free even though the operational :class:`Prospect` carries the address.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from enum import Enum
from typing import Literal

# Shared handoff vocab (kkg.2 / OBS-02), so outreach escalations read the same as
# the reply engine's (1mk.6) on the console: same escalation kinds + route enum.
from autonomy.decision import Escalation
from harness.state import RouteDecision

# Spec §5: 4 touches, widening gaps (day 0 / +3 / +5 / +7).
TOUCH_DAY_OFFSETS: tuple[int, ...] = (0, 3, 5, 7)
MAX_TOUCHES = 4


class Disposition(str, Enum):
    """What the engine decided for a prospect — none of these auto-sends."""

    ESCALATE = "escalate"                 # plan built, routed to human review (439)
    SKIP_SUPPRESSED = "skip_suppressed"   # on the do-not-contact list
    BLOCK_UNDELIVERABLE = "block_undeliverable"  # failed deliverability verification
    HARD_STOP = "hard_stop"               # reply/bounce/unsubscribe seen — sequence halted


VerificationStatus = Literal["deliverable", "risky", "undeliverable"]
StopReason = Literal["reply", "bounce", "unsubscribe", "spam_complaint"]


def prospect_ref(email: str, *, salt: str = "scalers") -> str:
    """Opaque, stable reference for a prospect — sha256(salt:lower(email))[:16].
    Used in plans/logs so no raw email (PII) is persisted in the audit trail."""
    norm = email.strip().lower()
    return hashlib.sha256(f"{salt}:{norm}".encode()).hexdigest()[:16]


@dataclass(frozen=True)
class Prospect:
    """One outreach target (operational; carries the address — keep out of logs)."""

    email: str
    name: str | None = None
    # Allowed, non-creepy personalization signals (e.g. public studio style, a
    # past inquiry topic). NEVER private/identifying attributes — the guard checks.
    signals: tuple[str, ...] = ()
    # Why we may contact them (past inquiry, event signup, opted-in partner). Cold
    # spray with no basis is out of scope — outreach is consent-aware.
    consent_basis: str | None = None

    @property
    def ref(self) -> str:
        return prospect_ref(self.email)


@dataclass(frozen=True)
class SuppressionResult:
    suppressed: bool
    reason: str | None = None


@dataclass(frozen=True)
class VerificationVerdict:
    """Deterministic deliverability verdict (no broker enrichment, no send)."""

    status: VerificationStatus
    reasons: tuple[str, ...] = ()

    @property
    def can_send(self) -> bool:
        # risky requires human review (escalate); undeliverable is blocked.
        return self.status == "deliverable"


@dataclass(frozen=True)
class Touch:
    """One step in the capped sequence. Copy is generated by the writer's
    copywriter cell (1mk.5) grounded in brand-voice (S2); this carries the slot
    + purpose + the personalization brief, not final prose."""

    index: int                         # 1..MAX_TOUCHES
    day_offset: int                    # 0 / 3 / 5 / 7
    purpose: str                       # e.g. "intro", "value-add", "soft-CTA", "break-up"
    personalization_brief: tuple[str, ...] = ()  # which allowed signals to reference
    includes_unsubscribe: bool = True  # RFC 8058 one-click — required on every touch


@dataclass(frozen=True)
class OutreachSequence:
    touches: tuple[Touch, ...]
    cap_per_inbox_day: int             # warmup-aware daily cap applied at schedule

    @property
    def length(self) -> int:
        return len(self.touches)


@dataclass(frozen=True)
class OutreachPlan:
    """The auditable outreach decision for one prospect. PII-free (ref only).
    ``routed_to`` is always 'review' under the 439 hold — never auto-sent."""

    prospect_ref: str
    disposition: Disposition
    suppression: SuppressionResult
    verification: VerificationVerdict | None = None
    sequence: OutreachSequence | None = None
    warnings: tuple[str, ...] = ()     # over-personalization / deliverability cautions
    # Shared handoff vocab with the reply engine (1mk.6): route is always REVIEW
    # under the 439 hold; escalation.kind/label drives the console escalation chip.
    route: RouteDecision = RouteDecision.REVIEW
    escalation: Escalation | None = None
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def routed_to(self) -> str:
        """Back-compat string view of ``route`` (always 'review' under 439)."""
        return self.route.value

    @property
    def will_send(self) -> bool:
        # Always False under 439 — present so a test can assert the hold holds.
        return self.route is RouteDecision.AUTO
